# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3f1e837976e82bc22e57489dd445a471828aa3a9f5bc82bb0c031f742c34356ae9dcbedff4dcb72e62419a411f3cdb8a6d36fc846112b4bb6ebd77171217675a

test:
  secret_key_base: a11b78130ed34fc83978a66c9674a99b70da334afd6281dc838ac771bee81703b71021abd78bddb8eaa3da266558c0911a75ff4ff3b0262700bf85120c6135e0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
